version: '3.8'

services:
  jellynouncer:
    build: .
    container_name: jellynouncer
    restart: unless-stopped
    ports:
      - "1984:1984"  # Webhook service
    environment:
      # Required Configuration
      - JELLYFIN_SERVER_URL=${JELLYFIN_SERVER_URL:-http://jellyfin:8096}
      - JELLYFIN_API_KEY=${JELLYFIN_API_KEY}
      - JELLYFIN_USER_ID=${JELLYFIN_USER_ID}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      
      # Optional: Content-specific webhooks
      - DISCORD_WEBHOOK_URL_MOVIES=${DISCORD_WEBHOOK_URL_MOVIES}
      - DISCORD_WEBHOOK_URL_TV=${DISCORD_WEBHOOK_URL_TV}
      - DISCORD_WEBHOOK_URL_MUSIC=${DISCORD_WEBHOOK_URL_MUSIC}
      
      # Optional: External API keys for enhanced metadata
      - OMDB_API_KEY=${OMDB_API_KEY}
      - TMDB_API_KEY=${TMDB_API_KEY}
      - TVDB_API_KEY=${TVDB_API_KEY}
      
      # Optional: Security
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      
      # System Configuration
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - JELLYNOUNCER_RUN_MODE=${JELLYNOUNCER_RUN_MODE:-all}  # all, webhook, or background
      
    volumes:
      # Persistent data
      - ./config:/app/config
      - ./data:/app/data
      - ./logs:/app/logs
      - ./templates:/app/templates
      
      # Optional: Custom web assets
      # - ./web/custom:/app/web/dist/assets:ro
      
    healthcheck:
      test: ["CMD", "python", "/app/healthcheck.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
      
    networks:
      - jellyfin-network
      
    # Optional: Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

networks:
  jellyfin-network:
    external: true
    # If you don't have a jellyfin network, comment above and uncomment below:
    # driver: bridge