name: Feature Request
description: Suggest a new feature or enhancement for Jellynouncer
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Please fill out this form as completely as possible.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-flight checklist
      description: Please ensure you've completed these steps before submitting your feature request.
      options:
        - label: I have searched for [existing issues](https://github.com/MarkusMcNugen/Jellynouncer/issues) and [discussions](https://github.com/MarkusMcNugen/Jellynouncer/discussions) to see if this feature has already been requested.
          required: true
        - label: I have read the [README](https://github.com/MarkusMcNugen/Jellynouncer/blob/main/README.md) to understand current functionality.
          required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see added.
      placeholder: Describe the feature you'd like to see...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: This feature would help with...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How do you think this feature should work? Be as specific as possible.
      placeholder: I think it should work like...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I've also considered...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my use of Jellynouncer
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple - Small change or addition
        - Medium - Moderate development effort
        - Complex - Significant development effort
        - I don't know
    validations:
      required: true

  - type: checkboxes
    id: areas
    attributes:
      label: Areas Affected
      description: Which areas of Jellynouncer would this feature affect? (Select all that apply)
      options:
        - label: Webhook processing
        - label: Discord notifications
        - label: Template system
        - label: Web interface
        - label: Configuration
        - label: Database/Storage
        - label: External API integrations
        - label: Docker deployment
        - label: Documentation

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: If applicable, add mockups, screenshots, or examples to help illustrate your feature request.
      placeholder: You can drag and drop images here...

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, links, or examples about the feature request here.
      placeholder: Additional information...