name: Cleanup Old Images

on:
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch:

jobs:
  cleanup-old-images:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Delete old Docker images
        uses: vlaurin/action-ghcr-prune@v0.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          organization: ${{ github.repository_owner }}
          container: jellynouncer
          keep-younger-than: 30 # Keep images newer than 30 days
          keep-last: 10 # Keep at least 10 images
          prune-untagged: true
          prune-tags-regexes: |
            ^pr-.*
            ^dev$
            ^.*-\d+$

  cleanup-old-artifacts:
    runs-on: ubuntu-latest
    permissions:
      actions: write

    steps:
      - name: Delete old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '30 days'
          skip-recent: 5